version: "3.8"
services:
        db:
                image: mysql:5.7
                ports:
                        - 3306:3306
                command: --secure-file-priv=/var/lib/mysql-files
                environment:
                        - "MYSQL_ROOT_PASSWORD=root123"
                        - "MYSQL_DATABASE=parcial1"
                        - "MYSQL_USER=test"
                        - "MYSQL_PASSWORD=test123"
                volumes: 
                        - "./sql_scripts:/docker-entrypoint-initdb.d"
                        - "./data:/var/lib/mysql-files"
                networks:
                        parcial1_net:
                                ipv4_address: 172.28.1.1
        rstudio:
                image: rocker/tidyverse
                ports:
                        - 8787:8787
                        - 3838:3838
                environment:
                        - "DISABLE_AUTH=true"
                        - "ADD=shiny"
                volumes:
                        - "./app:/home/rstudio"
                networks:
                        parcial1_net:
                                ipv4_address: 172.28.1.2
networks:
        parcial1_net:
                ipam:
                        driver: default
                        config:
                                - subnet: 172.28.0.0/16

