version: "3.8"
services:
        db:
                image: mysql
                ports:
                        - 3306:3306
                environment:
                        - "MYSQL_ROOT_PASSWORD=root123"
                        - "MYSQL_DATABASE=test"
                        - "MYSQL_USER=test"
                        - "MYSQL_PASSWORD=test123"
        jupyter:
                image: jupyter/datascience-notebook
                ports:
                        - 8888:8888
                depends_on:
                        - db
